# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  run:
    cmds:
      - uv run manage.py runserver

  showapi:
    cmds:
      - uv run manage.py show_urls

  migration:
    cmds:
      - uv run manage.py makemigrations
  migrate:
    cmds:
      - uv run manage.py migrate
  shell:
    cmds:
      - uv run manage.py shell_plus
